# Generated by Django 4.2.2 on 2023-07-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
